/*
 * KitInfo2.h
 *
 *  Created on: 17/04/2012
 *      Author: Grupo de profesores INFORMATICA 2
 */

#ifndef KIT_INFO2_H_
#define KIT_INFO2_H_

#include "Regs.h"


#define	EXPANSION	EXPANSION2

#define NINGUNO		0
#define EXPANSION1	1
#define	EXPANSION2	2
#define	EXPANSION3	3
#define	EXPANSION4	4

//Leds (Reles)
#define		LED0_PORT	GPIO2
#define		LED0_PIN	0

#define		LED1_PORT	GPIO0
#define		LED1_PIN	23

#define		LED2_PORT	GPIO0
#define		LED2_PIN	21

#define		LED3_PORT	GPIO0
#define		LED3_PIN	27

//Led RGB:
#define		RGBR_PORT	GPIO2
#define		RGBR_PIN	1

#define		RGBG_PORT	GPIO2
#define		RGBG_PIN	2

#define		RGBB_PORT	GPIO2
#define		RGBB_PIN	3

#define		BUZZ_PORT	GPIO0
#define		BUZZ_PIN	28

//Teclas (teclado 4x1)
#define		KEY0_PORT	GPIO2
#define		KEY0_PIN	10
#define		KEY0		((KEY0_PORT.FIOPIN&(1<<KEY0_PIN))>>KEY0_PIN)

#define		KEY1_PORT	GPIO0
#define		KEY1_PIN	18
#define		KEY1		((KEY1_PORT.FIOPIN&(1<<KEY1_PIN))>>KEY1_PIN)

#define		KEY2_PORT	GPIO0
#define		KEY2_PIN	11
#define		KEY2		((KEY2_PORT.FIOPIN&(1<<KEY2_PIN))>>KEY2_PIN)

#define		KEY3_PORT	GPIO2
#define		KEY3_PIN	13
#define		KEY3		((KEY3_PORT.FIOPIN&(1<<KEY3_PIN))>>KEY3_PIN)

#define		KEYRC_PORT	GPIO1
#define		KEYRC_PIN	26
#define		KEYRC		((KEYRC_PORT.FIOPIN&(1<<KEYRC_PIN))>>KEYRC_PIN)

//Entradas digitales:
#define		IN0_PORT	GPIO4
#define		IN0_PIN		29
#define		IN0			((IN0_PORT.FIOPIN&(1<<IN0_PIN))>>IN0_PIN)

#define		IN1_PORT	GPIO2
#define		IN1_PIN		11
#define		IN1			((IN1_PORT.FIOPIN&(1<<IN1_PIN))>>IN1_PIN)

//GPIOS LCD:
#define		LCD_D4_PORT	GPIO0
#define		LCD_D4_PIN	5

#define		LCD_D5_PORT	GPIO0
#define		LCD_D5_PIN	10

#define		LCD_D6_PORT	GPIO2
#define		LCD_D6_PIN	4

#define		LCD_D7_PORT	GPIO2
#define		LCD_D7_PIN	5

#define		LCD_RS_PORT	GPIO2
#define		LCD_RS_PIN	6

#define		LCD_BF_PORT	GPIO1
#define		LCD_BF_PIN	28

#define		LCD_E_PORT	GPIO0
#define		LCD_E_PIN	4

//UARTs
#define	TX0D_PORT	GPIO0
#define	TX0D_PIN	2

#define	RX0D_PORT	GPIO0
#define	RX0D_PIN	3

#define	TX1D_PORT	GPIO0
#define	TX1D_PIN	15

#define	RX1D_PORT	GPIO0
#define	RX1D_PIN	16

//ADC y DAC:
#define DAC_PORT	GPIO0
#define DAC_PIN		26

#define	ADC0_PORT	GPIO0
#define ADC0_PIN	23

#define	ADC1_PORT	GPIO0
#define ADC1_PIN	24

#define	ADC2_PORT	GPIO0
#define ADC2_PIN	25

#define	ADC3_PORT	GPIO0
#define ADC3_PIN	26

#define	ADC4_PORT	GPIO1
#define ADC4_PIN	30

#define	ADC5_PORT	GPIO1
#define ADC5_PIN	31

#define	ADC6_PORT	GPIO0
#define ADC6_PIN	3

#define	ADC7_PORT	GPIO0
#define ADC7_PIN	2

//Puertos de expansion:

#define PORT_EXPANSION0	GPIO2
#define	PIN_EXPANSION0	7

#define PORT_EXPANSION1	GPIO1
#define	PIN_EXPANSION1	29

#define PORT_EXPANSION2	GPIO4
#define	PIN_EXPANSION2	28

#define PORT_EXPANSION3	GPIO1
#define	PIN_EXPANSION3	23

#define PORT_EXPANSION4	GPIO1
#define	PIN_EXPANSION4	20

#define PORT_EXPANSION5	GPIO0
#define	PIN_EXPANSION5	19

#define PORT_EXPANSION6	GPIO3
#define	PIN_EXPANSION6	26

#define PORT_EXPANSION7	GPIO1
#define	PIN_EXPANSION7	25

#define PORT_EXPANSION8	GPIO1
#define	PIN_EXPANSION8	22

#define PORT_EXPANSION9	GPIO1
#define	PIN_EXPANSION9	19

#define PORT_EXPANSION10	GPIO0
#define	PIN_EXPANSION10	20

#define PORT_EXPANSION11	GPIO3
#define	PIN_EXPANSION11	25

#define PORT_EXPANSION12	GPIO1
#define	PIN_EXPANSION12	27

#define PORT_EXPANSION13	GPIO1
#define	PIN_EXPANSION13	24

#define PORT_EXPANSION14	GPIO1
#define	PIN_EXPANSION14	21

#define PORT_EXPANSION15	GPIO1
#define	PIN_EXPANSION15	18

#define PORT_EXPANSION16	GPIO1
#define	PIN_EXPANSION16	31

#define PORT_EXPANSION17	GPIO0
#define	PIN_EXPANSION117	24

#define PORT_EXPANSION18	GPIO0
#define	PIN_EXPANSION18	25

#define PORT_EXPANSION19	GPIO0
#define	PIN_EXPANSION19	17

#define PORT_EXPANSION20	GPIO0
#define	PIN_EXPANSION20	22

#define PORT_EXPANSION21	GPIO0
#define	PIN_EXPANSION21	15

#define PORT_EXPANSION22	GPIO0
#define	PIN_EXPANSION22	16

#define PORT_EXPANSION23 GPIO2
#define	PIN_EXPANSION23	8

#define PORT_EXPANSION24	GPIO2
#define	PIN_EXPANSION24	12

#define	PORT_LED1EXP1	PORT_EXPANSION0
#define	PIN_LED1EXP1	PIN_EXPANSION0

#define	PORT_DGT5EXP2	PORT_EXPANSION0
#define	PIN_DGT5EXP2	PIN_EXPANSION0

#define	PORT_BCDAEXP3	PORT_EXPANSION0
#define	PIN_BCDAEXP3	PIN_EXPANSION0

#define	PORT_ROW7EXP4	PORT_EXPANSION0
#define	PIN_ROW7EXP4	PIN_EXPANSION0

#define	PORT_LED2EXP1	PORT_EXPANSION1
#define	PIN_LED2EXP1	PIN_EXPANSION1

#define	PORT_DGT4EXP2	PORT_EXPANSION1
#define	PIN_DGT4EXP2	PIN_EXPANSION1

#define	PORT_BCDBEXP3	PORT_EXPANSION1
#define	PIN_BCDBEXP3	PIN_EXPANSION1

#define	PORT_ROW6EXP4	PORT_EXPANSION1
#define	PIN_ROW6EXP4	PIN_EXPANSION1

#define	PORT_LED3EXP1	PORT_EXPANSION2
#define	PIN_LED3EXP1	PIN_EXPANSION2

#define	PORT_DGT3EXP2	PORT_EXPANSION2
#define	PIN_DGT3EXP2	PIN_EXPANSION2

#define	PORT_BCDCEXP3	PORT_EXPANSION2
#define	PIN_BCDCEXP3	PIN_EXPANSION2

#define	PORT_ROW5EXP4	PORT_EXPANSION2
#define	PIN_ROW5EXP4	PIN_EXPANSION2

#define	PORT_LED4EXP1	PORT_EXPANSION3
#define	PIN_LED4EXP1	PIN_EXPANSION3

#define	PORT_DGT2EXP2	PORT_EXPANSION3
#define	PIN_DGT2EXP2	PIN_EXPANSION3

#define	PORT_BCDDEXP3	PORT_EXPANSION3
#define	PIN_BCDDEXP3	PIN_EXPANSION3

#define	PORT_ROW4EXP4	PORT_EXPANSION3
#define	PIN_ROW4EXP4	PIN_EXPANSION3

#define	PORT_LED5EXP1	PORT_EXPANSION4
#define	PIN_LED5EXP1	PIN_EXPANSION4

#define	PORT_DGT1EXP2	PORT_EXPANSION4
#define	PIN_DGT1EXP2	PIN_EXPANSION4

#define	PORT_DPEXP3		PORT_EXPANSION4
#define	PIN_DPEXP3		PIN_EXPANSION4

#define	PORT_ROW3EXP4	PORT_EXPANSION4
#define	PIN_ROW3EXP4	PIN_EXPANSION4

#define	PORT_LED6EXP1	PORT_EXPANSION5
#define	PIN_LED6EXP1	PIN_EXPANSION5

#define	PORT_DGT0EXP2	PORT_EXPANSION5
#define	PIN_DGT0EXP2	PIN_EXPANSION5

#define	PORT_CLKEXP3	PORT_EXPANSION5
#define	PIN_CLKEXP3		PIN_EXPANSION5

#define	PORT_ROW2EXP4	PORT_EXPANSION5
#define	PIN_ROW2EXP4	PIN_EXPANSION5

#define	PORT_LED7EXP1	PORT_EXPANSION6
#define	PIN_LED7EXP1	PIN_EXPANSION6

#define	PORT_AEXP2		PORT_EXPANSION6
#define	PIN_AEXP2		PIN_EXPANSION6

#define	PORT_RSTEXP3	PORT_EXPANSION6
#define	PIN_RSTEXP3		PIN_EXPANSION6

#define	PORT_ROW1EXP4	PORT_EXPANSION6
#define	PIN_ROW1EXP4	PIN_EXPANSION6

#define	PORT_LED8EXP1	PORT_EXPANSION7
#define	PIN_LED8EXP1	PIN_EXPANSION7

#define	PORT_FILA0EXP3	PORT_EXPANSION7
#define	PIN_FILA0EXP3	PIN_EXPANSION7

#define	PORT_SEREXP4	PORT_EXPANSION7
#define	PIN_SEREXP4		PIN_EXPANSION7

#define	PORT_DIP1EXP1	PORT_EXPANSION8
#define	PIN_DIP1EXP1	PIN_EXPANSION8

#define	PORT_FILA1EXP3	PORT_EXPANSION8
#define	PIN_FILA1EXP3	PIN_EXPANSION8

#define	PORT_SRCLKEXP4	PORT_EXPANSION8
#define	PIN_SRCLKEXP4	PIN_EXPANSION8

#define	PORT_DIP2EXP1	PORT_EXPANSION9
#define	PIN_DIP2EXP1	PIN_EXPANSION9

#define	PORT_DPEXP2		PORT_EXPANSION9
#define	PIN_DPEXP2		PIN_EXPANSION9

#define	PORT_FILA2EXP3	PORT_EXPANSION9
#define	PIN_FILA2EXP3	PIN_EXPANSION9

#define	PORT_LCLKEXP4	PORT_EXPANSION9
#define	PIN_LCLKEXP4	PIN_EXPANSION9

#define	PORT_DIP3EXP1	PORT_EXPANSION10
#define	PIN_DIP3EXP1	PIN_EXPANSION10

#define	PORT_GEXP2		PORT_EXPANSION10
#define	PIN_GEXP2		PIN_EXPANSION10

#define	PORT_FILA3EXP3	PORT_EXPANSION10
#define	PIN_FILA3EXP3	PIN_EXPANSION10

#define	PORT_FILA0EXP4	PORT_EXPANSION10
#define	PIN_FILA0EXP4	PIN_EXPANSION10

#define	PORT_DIP4EXP1	PORT_EXPANSION11
#define	PIN_DIP4EXP1	PIN_EXPANSION11

#define	PORT_FEXP2		PORT_EXPANSION11
#define	PIN_FEXP2		PIN_EXPANSION11

#define	PORT_COL0EXP3	PORT_EXPANSION11
#define	PIN_COL0EXP3	PIN_EXPANSION11

#define	PORT_FILA1EXP4	PORT_EXPANSION11
#define	PIN_FILA1EXP4	PIN_EXPANSION11

#define	PORT_DIP5EXP1	PORT_EXPANSION12
#define	PIN_DIP5EXP1	PIN_EXPANSION12

#define	PORT_EEXP2		PORT_EXPANSION12
#define	PIN_EEXP2		PIN_EXPANSION12

#define	PORT_COL1EXP3	PORT_EXPANSION12
#define	PIN_COL1EXP3	PIN_EXPANSION12

#define	PORT_FILA2EXP4	PORT_EXPANSION12
#define	PIN_FILA2EXP4	PIN_EXPANSION12

#define	PORT_DIP6EXP1	PORT_EXPANSION13
#define	PIN_DIP6EXP1	PIN_EXPANSION13

#define	PORT_DEXP2		PORT_EXPANSION13
#define	PIN_DEXP2		PIN_EXPANSION13

#define	PORT_COL0EXP4	PORT_EXPANSION13
#define	PIN_COL0EXP4	PIN_EXPANSION13

#define	PORT_DIP7EXP1	PORT_EXPANSION14
#define	PIN_DIP7EXP1	PIN_EXPANSION14

#define	PORT_CEXP2		PORT_EXPANSION14
#define	PIN_CEXP2		PIN_EXPANSION14

#define	PORT_COL1EXP4	PORT_EXPANSION14
#define	PIN_COL1EXP4	PIN_EXPANSION14

#define	PORT_DIP8EXP1	PORT_EXPANSION15
#define	PIN_DIP8EXP1	PIN_EXPANSION15

#define	PORT_BEXP2		PORT_EXPANSION15
#define	PIN_BEXP2		PIN_EXPANSION15

#define	PORT_COL2EXP4	PORT_EXPANSION15
#define	PIN_COL2EXP4	PIN_EXPANSION15

#if EXPANSION == EXPANSION1

#define	DIP1			((PORT_DIP1EXP1.FIOPIN>>PIN_DIP1EXP1)&0x01)
#define	DIP2			((PORT_DIP2EXP1.FIOPIN>>PIN_DIP2EXP1)&0x01)
#define	DIP3			((PORT_DIP3EXP1.FIOPIN>>PIN_DIP3EXP1)&0x01)
#define	DIP4			((PORT_DIP4EXP1.FIOPIN>>PIN_DIP4EXP1)&0x01)
#define	DIP5			((PORT_DIP5EXP1.FIOPIN>>PIN_DIP5EXP1)&0x01)
#define	DIP6			((PORT_DIP6EXP1.FIOPIN>>PIN_DIP6EXP1)&0x01)
#define	DIP7			((PORT_DIP7EXP1.FIOPIN>>PIN_DIP7EXP1)&0x01)
#define	DIP8			((PORT_DIP8EXP1.FIOPIN>>PIN_DIP8EXP1)&0x01)

#endif

#if EXPANSION == EXPANSION3

#define	FILA0			((PORT_FILA0EXP3.FIOPIN>>PIN_FILA0EXP3)&0x01)
#define	FILA1			((PORT_FILA1EXP3.FIOPIN>>PIN_FILA1EXP3)&0x01)
#define	FILA2			((PORT_FILA2EXP3.FIOPIN>>PIN_FILA2EXP3)&0x01)
#define	FILA3			((PORT_FILA3EXP3.FIOPIN>>PIN_FILA3EXP3)&0x01)

#endif

#if EXPANSION == EXPANSION4

#define	FILA0			((PORT_FILA0EXP4.FIOPIN>>PIN_FILA0EXP4)&0x01)
#define	FILA1			((PORT_FILA1EXP4.FIOPIN>>PIN_FILA1EXP4)&0x01)
#define	FILA2			((PORT_FILA2EXP4.FIOPIN>>PIN_FILA2EXP4)&0x01)

#endif

//Defines generales:
#define		OFF			0
#define		ON			1

#define		LED_ON		1
#define		LED_OFF		0

#define		RGB_ON		1
#define		RGB_OFF		0

#define		BUZZ_ON		0
#define		BUZZ_OFF	1

#define		PRESIONADA	0
#define		SUELTA		1

#define		IN_ACTIVA	0
#define		IN_PASIVA	1

#define		DIRECCION(PORT,PIN,INOUT)(PORT.FIODIR)=((INOUT)==SALIDA?((PORT.FIODIR)|(0x01<<(PIN))):((PORT.FIODIR)&~(0x01<<(PIN))))
#define		SETPIN(PORT,PIN,STAT)(PORT.FIOPIN)=(STAT==1?(PORT.FIOPIN|(0x01<<PIN)):(PORT.FIOPIN&~(0x01<<PIN)))
#define		SETPINSEL(REG,BIT,VAL)\
			(REG)&=~(0x03<<(BIT));\
			(REG)|=((VAL)<<(BIT));

//Valores para configuracion del PLL:
#define CLOCK_SETUP_Value 	    1
#define SCS_Value				0x00000020
#define CLKSRCSEL_Value         0x00000001
#define PLL0_SETUP_Value        1
#define PLL0CFG_Value           0x00050063
#define PLL1_SETUP_Value        1
#define PLL1CFG_Value           0x00000023
#define CCLKCFG_Value           0x00000003
#define USBCLKCFG_Value         0x00000000
#define PCLKSEL0_Value          0x00000000
#define PCLKSEL1_Value          0x00000000
#define PCONP_Value             0x042887DE
#define CLKOUTCFG_Value         0x00000000
#define FLASHCFG_Value			0x00004000

#define XTAL        		(12000000UL)        /* Oscillator frequency               */
#define OSC_CLK     		(      XTAL)        /* Main oscillator frequency          */
#define RTC_CLK     		(   32000UL)        /* RTC oscillator frequency           */
#define IRC_OSC     		( 4000000UL)        /* Internal RC oscillator frequency   */

/* F_cco0 = (2 * M * F_in) / N  */
#define _M               	(((PLL0CFG_Value      ) & 0x7FFF) + 1)
#define _N               	(((PLL0CFG_Value >> 16) & 0x00FF) + 1)
#define _FCCO(_F_IN)    	((2ULL * _M * _F_IN) / _N)
#define _CCLK_DIV        	(((CCLKCFG_Value      ) & 0x00FF) + 1)

/* Determine core clock frequency according to settings */
#define CORE_CLK			(_FCCO(OSC_CLK) / _CCLK_DIV)

#endif /* KIT_INFO2_H_ */
